devices([
   "iPhone SE",
   "iPhone 7",
   "iPhone 7 Plus",
   "iPad Pro (9.7-inch)"
])
languages([
  "en-US"
])
scheme "books_UITests"
output_directory "./"
workspace "../../books.xcworkspace"
clear_previous_screenshots true
